### ISSUE TITLE
Bug in AuthenticationProviderProxyFactory

### ISSUE THREAD

**Issue by TorstenF76** [1and1/cosmo#10]
In [AuthenticationProviderProxyFactory Line 53](https://github.com/1and1/cosmo/blob/master/cosmo-core/src/main/java/org/unitedinternet/cosmo/acegisecurity/AuthenticationProviderProxyFactory.java#L53): 

```
52:                   UsernamePasswordAuthenticationToken result = new UsernamePasswordAuthenticationToken(userDetails, authentication.getCredentials(), authentication.getAuthorities());

53:                   result.setAuthenticated(authentication.isAuthenticated());
```

a call of result.setAuthenticated(true) raises an exception: 
```
	public void setAuthenticated(boolean isAuthenticated) throws IllegalArgumentException {
		if (isAuthenticated) {
			throw new IllegalArgumentException(
					"Cannot set this token to trusted - use constructor which takes a GrantedAuthority list instead");
		}

		super.setAuthenticated(false);
	}
```

the whole call of setAuthenticated is unnecessary as the property gets set directly within the constructor of UsernamePasswordAuthenticationToken. 

So please remove the line that tries to set the authenticated property, otherwise it is not possible to use a UsernamePasswordAuthenticationToken which has authenticated set to true.

**Comment by danielgrigore** [comment]
Solved in version 1.6.2 by passing the authorities as well.
