### ISSUE TITLE
When create new entity, error occurs

### ISSUE THREAD

**Issue by annous2019** [1and1/cosmo#19]
Hi. i set up Cosmo calDAV server successfully.
When i try to add new hibernate entity, the corresponding table is created in database
Next I create a new user in table users but when i try to get the user in java application the result is null 

below is the added entity 

@Entity
@Table(
    name = "user_accretio"
)
public class HibAccretioUser implements Serializable {
    private static final long serialVersionUID = 5144186861660046495L;
    @Id
    @GeneratedValue(
        strategy = GenerationType.AUTO
    )
    private int id;
    @Column(
        name = "registration_number",
        nullable = true,
        length = 255
    )
    @Length(
        min = 1,
        max = 255
    )
    private String registrationNumber;
    @Column(
        name = "calendar_id",
        nullable = true,
        length = 255
    )
    @Length(
        min = 1,
        max = 255
    )
    private String calendarId;
    @Column(
        name = "admin",
        nullable = true,
        length = 4
    )
    @Length(
        min = 1,
        max = 4
    )
    private int admin;

    public HibAccretioUser() {
    }

    public int getId() {
        return this.id;
    }
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }
    public String getCalendarId() {
        return this.calendarId;
    }
    public void setCalendarId(String calendarId) {
        this.calendarId = calendarId;
    }
    public int getAdmin() {
        return this.admin;
    }
    public void setAdmin(int admin) {
        this.admin = admin;
    }
    public String toString() {
        return "HibAccretioUser [registrationNumber=" + this.registrationNumber + ", calendarId=" + this.calendarId + ", admin=" + this.admin + "]";
    }
}

Do i misunderstand cosmo server specification or i made mistake?

**Comment by danielgrigore** [comment]
Hi @annous2019 
First of all, the demo application uses an in-memory MariaDB instance and everything you do when using the application is lost after you close it.
You say that the entity is saved but then you cannot find it (you could check that the data is actually saved in the database by connecting to the MariaDB instance using a mysql client). 
Maybe the "find" method does not work as expected.
Cheers,
