### ISSUE TITLE
Event save in DB but not reflect or sync with Evolution calendar

### ISSUE THREAD

**Issue by sdongare** [1and1/cosmo#23]
I created new  custom REST service in Web app to create user and insert event in system. User created and its access account by evolution client. but when I create event by REST service, its save in DB but same event not reflect or sync with Calender (Evolution).
   is any missing to create event by custom REST service or something need extra to reflect event to calender. i compared DB entry when create event by evolution calendar and by my custom API. in item table , "itemname" save as 'note' instead of '...xxxxx.ics'..some thing wrong ? please help me.

**Comment by eardeleanu15** [comment]
I advice to check your Calendar client (Evolution) logs and see if you spot any errors during synchronization.
