### ISSUE TITLE
The problem remains

### ISSUE THREAD

**Issue by laodaobazi** [1and1/cosmo#3]
I'm sorry I think that in my workspace maybe missing a properties file .first run <b>mvn clean install</b> then run <b>mvn tomcat7:run-war</b>.the problem remains,like that:
INFO: Initializing Spring root WebApplicationContext
Dec 16, 2015 5:52:54 AM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization started
Dec 16, 2015 5:52:54 AM org.springframework.web.context.ContextLoader initWebApplicationContext
SEVERE: Context initialization failed
java.lang.NullPointerException
at java.util.Properties$LineReader.readLine(Properties.java:434)
at java.util.Properties.load0(Properties.java:353)
at java.util.Properties.load(Properties.java:341)
at org.unitedinternet.cosmo.servletcontext.ServletContextUtil.extractApplicationProperties(ServletContextUtil.java:31)
at org.unitedinternet.cosmo.servletcontext.CosmoApplicationContextInitializer.initialize(CosmoApplicationContextInitializer.java:21)
at org.unitedinternet.cosmo.servletcontext.CosmoApplicationContextInitializer.initialize(CosmoApplicationContextInitializer.java:13)
at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:450)
at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:402)

Can you give me a cosmo.war by Email ( the email address is 06libiao@sina.com )?   Thanks!

**Comment by danielpopa1986** [comment]
Hi laodaobazi,

Now version 0.95-SNAPSHOT should work.
Please assure that before running the "mvn tomcat7:run-war" command you made
- a mvn clean install in cosmo folder
- a mvn clean install also in cosmo-webapp module to clear all you old things.

I've tested last night and it worked for me.

If the problem still persist, another suggestion is to to make a new clone of the project to have a fresh copy of it.

Regards,
Daniel

**Comment by laodaobazi** [comment]
Hi Daniel ,

I make a new clone of the project to have a try , it is success !
but before running <b>mvn tomcat7:run-war</b> , I have to modify pom.xml in cosmo-webapp folder .
change 
<pre>
    &lt;parent&gt;
        &lt;artifactId&gt;cosmo-multimodule&lt;/artifactId&gt;
        &lt;groupId&gt;net.oneandone.cosmo&lt;/groupId&gt;
        &lt;version&gt;<b>0.95-SNAPSHOT</b>&lt;/version&gt;
    &lt;/parent&gt;
</pre>
to
<pre>
    &lt;parent&gt;
        &lt;artifactId&gt;cosmo-multimodule&lt;/artifactId&gt;
        &lt;groupId&gt;net.oneandone.cosmo&lt;/groupId&gt;
        &lt;version&gt;<b>0.95</b>&lt;/version&gt;
    &lt;/parent&gt;
</pre>
and change
<pre>
      &lt;dependency&gt;
            &lt;groupId&gt;net.oneandone.cosmo&lt;/groupId&gt;
            &lt;artifactId&gt;cosmo-core&lt;/artifactId&gt;
            &lt;version&gt;<b>0.95-SNAPSHOT</b>&lt;/version&gt;
        &lt;/dependency&gt;
</pre>
to
<pre>
      &lt;dependency&gt;
            &lt;groupId&gt;net.oneandone.cosmo&lt;/groupId&gt;
            &lt;artifactId&gt;cosmo-core&lt;/artifactId&gt;
            &lt;version&gt;<b>0.95</b>&lt;/version&gt;
        &lt;/dependency&gt;
</pre>

please change this pom.xml in <b>cosmo-multimodule-0.95.tar.gz</b> . Thanks !

**Comment by laodaobazi** [comment]
Then I want to know how can I use the cosmo .when I perform CalDAV requests to http://localhost:8080/cosmo/dav/root/calendar/ , the browser response that ：
<pre>
&lt;D:error&gt;&lt;cosmo:not-found/&gt;&lt;/D:error&gt;
</pre>

I've choosen mysql in my project . Which table need example calendar data in mysql . Can you give me a demo SQL ? thanks a lot .

**Comment by corneliudobrota** [comment]
Hi,

The available paths are /dav/users/{userEmail}, /dav/homeCollectionUid/,
/dav/homeCollectionUid/collectionUid/, /dav/homeCollectionUid/collectionUid/itemUid

So the not found status is correct

**Comment by laodaobazi** [comment]
Although normal running of the project , but I don't know that how to configure on my iphone with cosmo now . Do you know that ?

**Comment by laodaobazi** [comment]
The cosmo is perfect ! 
I think I can use my iphone as a client and cosmo as a caldav server . 
Thanks @corneliudobrota  and @danielpopa1986 .

Regards,
laodaobazi

**Comment by danielpopa1986** [comment]
Hi laodaobazi,

We are happy that you can use it.
You can also use cosmo in the webapp directly by injecting the server dependencies from the Maven repository:
http://mvnrepository.com/artifact/net.oneandone.cosmo/cosmo-core/0.95
http://mvnrepository.com/artifact/net.oneandone.cosmo/cosmo-api/0.95
You can replace 0.96-SNAPSHOT dependency from webapp pom.xml with the version above for an easier use and for keeping this version.

Regards,
Daniel
