### ISSUE TITLE
Shared calendar

### ISSUE THREAD

**Issue by annous2019** [1and1/cosmo#30]
Hello team,
I would like to know if cosmo can support calendar sharing between users

Best Regards

**Comment by danielgrigore** [comment]
Hi @annous2019 
Yes, cosmo is able to support calendar sharing between users (via tickets).
Please have a look at [org.unitedinternet.cosmo.model.CollectionSubscription](https://github.com/1and1/cosmo/blob/master/cosmo-api/src/main/java/org/unitedinternet/cosmo/model/CollectionSubscription.java) interface and at it's implementation [org.unitedinternet.cosmo.model.hibernateHibCollectionSubscription](https://github.com/1and1/cosmo/blob/master/cosmo-core/src/main/java/org/unitedinternet/cosmo/model/hibernate/HibCollectionSubscription.java).
Cheers,
