### ISSUE TITLE
Shared calendar

### ISSUE THREAD

**Issue by annous2019** [1and1/cosmo#32]
hello team, 

For sharing a calendar between users I used org.unitedinternet.cosmo.model.CollectionSubscription interface and its implementation org.unitedinternet.cosmo.model.hibernateHibCollectionSubscription.
 
How can I test the result with a client like nextcloud or other

Best Regards

**Comment by danielgrigore** [comment]
Hi @annous2019,

For testing cosmo functionalities you would need a CalDAV client, like Mozilla Lightning, Apple native client, or similar.
You could also try with `curl` from linux, but you need to build yourself the XML body requests.

Cheers,
