### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by annous2019** [1and1/cosmo#39]
Hello Team,

Is there any public docker image for cosmo caldav server

Best Regards

**Comment by danielgrigore** [comment]
Hi @annous2019,
So far there is no docker image for cosmo. 
The reasons for which we did not took into consideration building a docker image are the following:
- cosmo demo application uses an in-memory database and data is lost with every restart. 
- the authenticating system is one that allows anyone to connect (it automatically provisions an account if there isn't one already).
Most probably someone that wants to use cosmo will modify the persistence system and will configure a more powerful authenticating system.
If you want to run the demo application please have a look at the README.MD file
Cheers,
