### ISSUE TITLE
cosmo not match Oracle

### ISSUE THREAD

**Issue by laodaobazi** [1and1/cosmo#4]
The database choose MySQL is OK , but when I run cosmo with Oracle have some problems.
for example : 'item' , 'users' , 'uid' and so on , These words are Oracle  reserved keywords .
Do you run cosmo with Oracle ?

Regards.

**Comment by danielpopa1986** [comment]
Hi laodaobazi,

The database we are currently using cosmo with is MySQL.

Regards,
Daniel
