### ISSUE TITLE
is possible to subscribe users to particular user event ?

### ISSUE THREAD

**Issue by sdongare** [1and1/cosmo#42]
is possible to create event one time for user  and share same event with other user when he wants like subscription? if possible please give hint. thanks in advance.

**Comment by danielgrigore** [comment]
Hi @sdongare,

I don't know if I understood your question correctly, but it is possible to create a ticket of type `read_write` and attach it to an item. With that ticket another user can modify the item.

 `Item item = new HibNoteItem();`
 `Ticket ticket = this.entityFactory.createTicket(TicketType.READ_WRITE);`
` ticket.setOwner(item.getOwner());`
` ticket.setTimeout(Ticket.TIMEOUT_INFINITE);`
` String ticketKey = generateTicketKey("someEmailAddress@some.some");`
` ticket.setKey(ticketKey);`
` this.contentService.createTicket(item, ticket);` 

You will have to create your own method for generating the ticket keys.
Hope this helps.
Cheers,

**Comment by sdongare** [comment]
Thank you.
