### ISSUE TITLE
pom needs update in protocoll for jcenter repository

### ISSUE THREAD

**Issue by pkerspe** [1and1/cosmo#43]
In the current version of the pom the repositoy is defined as:

```
<repositories>
		<!-- Embedded Maria DB. -->
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
	</repositories>
```

Jcenter is only reachable via https though, thus maven fails to connect.
Please update repository URL to https protocol:

`<url>https://jcenter.bintray.com</url>`

**Comment by danielgrigore** [comment]
Thank you for feedback, @pkerspe.
I updated the pom.xml file.
Cheers,
