### ISSUE TITLE
Are there any options to share .ics links of an existing collection?

### ISSUE THREAD

**Issue by slincem** [1and1/cosmo#45]
Hi @danielgrigore 

In our team, we already implemented the subscriptions with the corresponding ticket to share calendar with a specific user, or just for creating a public link sending those tickets. 

However, now we are working on a feature for sharing the collections that we have in Cosmo with another one who is outside from it and that is using a client which supports .ics instead of Caldav. We think we can achieve this turning the collection into a ICS file and expose it in a public link, so external people would be able to import it.

Is this behavior or something similar already implemented in Cosmo?.

Cheers,

**Comment by danielgrigore** [comment]
Hi @slincem
 
There is something that is related to your described scenario.
You can have a look at `CalendarCollectionProvider` class.
Here's how a curl command will look like.

`curl -XGET -H"Accept: text/calendar" "http://localhost:8081/cosmo/dav/item/7b4129fa-ee25-44d2-93d5-271230d678cf?ticket=e65db84c-248b-4754-a435-ceed02ce0bbd"`
First path parameter after item represents the UID of the calendar and obviously you also need the ticket as query parameter.

Cheers,

**Comment by slincem** [comment]
Hi @danielgrigore 

Thanks for your help!. We follow ur advice with some small changes based on our business rules and it works.
