### ISSUE TITLE
is there a specific health check url for an instance

### ISSUE THREAD

**Issue by f1-outsourcing** [1and1/cosmo#50]
Sorry for harassing so much here, as you maybe noticed I am testing with your application. Looks promising!

Anyway for container deployments it is always nice to have some health check url to use. Is there a some endpoint I can use for this that does not require authentication? (sorry do not know to much about the caldav standard). If so, maybe nice to put in the readme

**Comment by danielgrigore** [comment]
There isn't a health check included. But one can be added easily.
Please have a look at `spring-boot-starter-actuator` library.
Cheers,
