### ISSUE TITLE
How are alarms triggered currently?

### ISSUE THREAD

**Issue by manjirinamjoshi** [1and1/cosmo#54]
I am fairly new to iCal world. But, wondering how is VALARM trigger is implemented in this server?

**Comment by danielgrigore** [comment]
Hi @manjirinamjoshi 
If you are asking about how reminders are sent (email, SMS etc.), then the answer is: that is left to be decided by the applications that will include/extend cosmo, because obviously this will be specific to each application.
Cheers,

**Comment by manjirinamjoshi** [comment]
Thank you for your reply. Another related question - does cosmo call any webhook for event create/update/delete?

**Comment by danielgrigore** [comment]
Hi @manjirinamjoshi 
Please have a look at [interceptors](https://github.com/1and1/cosmo/tree/master/cosmo-api/src/main/java/org/unitedinternet/cosmo/service/interceptors) package.
You can find some simple implementation of some of them in the demo [cosmo-webapp](https://github.com/1and1/cosmo/tree/master/cosmo-webapp/src/main/java/org/unitedinternet/cosmo/service/interceptors).
Cheers,
