### ISSUE TITLE
Hibernate Exception on deploy

### ISSUE THREAD

**Issue by daorte** [1and1/cosmo#6]
Hi!
i did make a clone from master branch on Netbeans, after a 'clean and build' and 'run' i got this Exception:

`org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.unitedinternet.cosmo.db.DbListener
 org.hibernate.HibernateException: Wrong column type in cosmo.event_stamp for column isfloating. Found: tinyint, expected: bit`

And the deploy stop
- Apache Tomcat 8.0.33
- MySQL 5.6.28
- MySQL connector 5.1.38

Thanks in advance for your help

**Comment by danielgrigore** [comment]
Hi,

The demo application was running Hypersonic DB which could not full understand cosmo SQL files.
I updated the demo application to use embedded Maria DB on port 33060.
Everything should work fine now.

Thanks for your support.
