### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by Dexterxd18312** [1and1/cosmo#62]
Hi,
I have a few question about the functionality of cosmo. I am on macOS.
1_ Can I use mamp as a host? If I can how to connect the two things?
2_I never used spring, how it works?

**Comment by danielgrigore** [comment]
Hi @Dexterxd18312 
I'm not a Mac user myself, but I had a look briefly at mamp documentation and I think you do not need that.
The cosmo can be run as spring boot application in an embedded Tomcat container.
Please have a look at the cosmo-webapp demo application. For Spring documentation you can start at https://spring.io/
Cheer,
