### ISSUE TITLE
cosmo-api.jar

### ISSUE THREAD

**Issue by matizakoo** [1and1/cosmo#68]
Hi Daniel

When I tried to run application (cosmo-core) I started with mvn clean package and I get very weird exception. I was looking for some information on the internet etc. but nothing works. Maybe you know how to deal with the .jar file.

Thank you for your help

Could not resolve dependencies for project net.oneandone.cosmo:cosmo-core:jar:5.0.1-SNAPSHOT: The following artifacts could not be resolved: net.oneandone.cosmo:cosmo-api:jar:5.0.1-SNAPSHOT (absent): Could not find artifact net.oneandone.cosmo:cosmo-api:jar:5.0.1-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project cosmo-core: Could not resolve dependencies for project net.oneandone.cosmo:cosmo-core:jar:5.0.1-SNAPSHOT: The following artifacts could not be resolved: net.oneandone.cosmo:cosmo-api:jar:5.0.1-SNAPSHOT (absent): Could not find artifact net.oneandone.cosmo:cosmo-api:jar:5.0.1-SNAPSHOT

**Comment by danielgrigore** [comment]
Hi @matizakoo 
`cosmo-core` is not an application, `cosmo-webapp` is a spring-boot application.

Cheers,
