### ISSUE TITLE
How to deploy

### ISSUE THREAD

**Issue by daorte** [1and1/cosmo#7]
Hi, sorry for open an issue to ask a question but i can not find any way to contact you.

I'm really interested in your project but until now i can not make it run on "my environment"

I need to use the Cosmo CalDAV server, connected to an independent MySQL (not embeded) and use the API to make calendar operations from other Java EE application (other server)

How can i configure/deploy Cosmo to get it running for that?

Thanks in advance and sorry again

**Comment by corneliudobrota** [comment]
Hi,

You should provide the minimum:
-a DataSourceProvider implementation and
-an AuthenticationProvider implementation.

Cosmo searches when application context is started for those. It also
injects required services into your Spring beans or, if you don't have a
Spring context simply, creates instances of classes that require services
and injects the services into them.

The demo web-app is a starting point candidate. You could create you data
source there and an AuthenticationProvider.

Regards,
Cornel
