### ISSUE TITLE
future developments for cosmo? encryption?

### ISSUE THREAD

**Issue by f1-outsourcing** [1and1/cosmo#71]
I was wondering if there is any idea about how to proceed in the future with cosmo. I saw this calendar stuff at proton mail and it looks quite nice have this 'end to end' encryption. Maybe there is a standard for encrypting caldav entries?

https://proton.me/blog/protoncalendar-security-model

**Comment by cosminh11** [comment]
There aren't any plans for end-to-end encryption as far as I'm aware  of.
