### ISSUE TITLE
tuning advices

### ISSUE THREAD

**Issue by f1-outsourcing** [1and1/cosmo#79]
Hi Daniel,

I was wondering if there are some tuning advices for either java or mariadb for this caldav specific use? I did (again) some tests with the demo application and when I put 400 times a calendar item I am getting a lot of 423 and 500 responses with only(?) 8 requests/sec

**Comment by danielgrigore** [comment]
I really can't give any advice here. There are too many variables to take into account.

You need to estimate the load you expect and configure the necessary resources on the server side (like number of vm-s, pods, memory, cpu-s etc.) and also tune the DB parameters like memory, innodb buffer etc.

Cheers,
