### ISSUE TITLE
Disabling hibernate statistics in webapp

### ISSUE THREAD

**Issue by porkotron** [1and1/cosmo#8]
It seems that setting hibernate.generate_statistics=false in application.properties or System properties has no effect. Is there a way to disable statistics currently?

**Comment by danielgrigore** [comment]
Hi Petri,
The statistics logging is something internal to Hibernate and it was activated together with Hibernate 5. 
We overcome this issue by setting the logging level to 'WARN' for hibernate engine in[ logback.xml ](https://github.com/1and1/cosmo/blob/master/cosmo-webapp/src/main/resources/applicationContext.xml)file.
`<logger name="org.hibernate.engine" level="WARN"/>`
Most probably this solution could also work for you.
Cheers.

**Comment by porkotron** [comment]
I'm using log4j and setting equivalent property in log4j.properties worked. Thanks Daniel!
