### ISSUE TITLE
authentication (provider) stateless rest api

### ISSUE THREAD

**Issue by f1-outsourcing** [1and1/cosmo#80]
@danielgrigore  Hi Daniel, 

I have sort of something that authenticates with an external ldap. First thing I am noticing is that every request is authenticating against ldap. I don't think this is currently an issue. But I was wondering if this is the default when implementing these authentication providers. I am unfamiliar with this caldav / dav and just read this somewhere about stateful and stateless rest apis, and was wondering what is the best practice. Should I try and add some session cookie, or is this ignored by many caldav clients?

Can you advice in any way on this?

**Comment by danielgrigore** [comment]
The CalDAV protocol is an extension of WebDAV protocol built on top of HTTP which is stateless.
Most probably the cookie will be ignored by the CalDAV clients.
