### ISSUE TITLE
Error on running curl -MKCALENDAR

### ISSUE THREAD

**Issue by dyana0123** [1and1/cosmo#81]
Hello when running ' curl -X"MKCALENDAR" -H"Content-Type:application/xml" -u${email}:${password} http://localhost:8080/cosmo/dav/{email}/calendar" ' I get the following error:
<?xml version="1.0" ?><D:error xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:cosmo="http://osafoundation.org/cosmo/DAV" xmlns:D="DAV:"><C:calendar-collection-location-ok>One or more intermediate collections must be created</C:calendar-collection-location-ok></D:error>

I'm running the application with a local instance of mariadb.
Can you help me understand what can I do to make it work?

**Comment by f1-outsourcing** [comment]
Looks like there is nothing wrong with your request, I have been using the same for a while without issues.

`curl -k -X "MKCALENDAR" -H "Content-Type:application/xml" -u "$user:$password" "$caldavurl/$user/calendar"`

Maybe your databases is not properly initialized? Maybe delete everything of this user in the database?

**Comment by danielgrigore** [comment]
I ran the following command:
`curl -i -X"MKCALENDAR" -H"Content-Type:application/xml" -ujon.doe@some.dev:sample http://localhost:8080/cosmo/dav/jon.doe@some.dev/calendar`

and i got a 201 status code

`HTTP/1.1 201 
Cache-control: no-cache
`
